AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CertificateArn:
    AllowedValues:
      - arn:aws:acm:us-east-1:435765244332:certificate/779f6a51-049f-466c-9a86-960e21c0453b
      - arn:aws:acm:us-east-1:403617656420:certificate/c63545fa-8d30-4023-aa23-68bf5f4ba62f
    Type: String

  CloudFrontHostedZoneId:
    AllowedValues:
      - Z03413242K12VXBMESSYC
      - Z06243561BJW62E9DPALB
    Type: String

  HostedZone:
    AllowedValues:
      - gracemedicalvillagedev.com
      - gracemedicalvillage.com
    Type: String

Resources:
  S3BucketForWebsite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref HostedZone
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HostedZone
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref HostedZone
                - /*
  S3WWWBucketForWebsite:
    Type: AWS::S3::Bucket
    DependsOn:
      - S3BucketForWebsite
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName: !Sub www.${HostedZone}
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref S3BucketForWebsite
          Protocol: https
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - S3WWWBucketForWebsite
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref HostedZone
          - !Sub www.${HostedZone}
        Comment: !Sub CDN for ${HostedZone}
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: !Ref HostedZone
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            DomainName: !Sub ${HostedZone}.s3.amazonaws.com
            Id: !Ref HostedZone
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    DependsOn:
      - CloudfrontDistribution
    Properties:
      HostedZoneName: !Sub ${HostedZone}.
      RecordSets:
        - Name: !Ref HostedZone
          Type: A
          AliasTarget:
            DNSName: !GetAtt [CloudfrontDistribution, DomainName]
            EvaluateTargetHealth: false
            HostedZoneId: !Ref CloudFrontHostedZoneId
        - Name: !Sub www.${HostedZone}
          Type: A
          AliasTarget:
            DNSName: !GetAtt [CloudfrontDistribution, DomainName]
            EvaluateTargetHealth: false
            HostedZoneId: !Ref CloudFrontHostedZoneId

Outputs:
  CloudfrontDistribution:
    Value: !Ref CloudfrontDistribution
  WebsiteDNSName:
    Value: !Ref WebsiteDNSName
