AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ContactEmail:
    AllowedValues:
      - brettbotto+gmvdev@gmail.com
      - brettbotto+gmvprod@gmail.com
    Type: String

  Environment:
    AllowedValues:
      - development
      - production
    Type: String

  ProjectName:
    Default: GraceMedicalVillage
    Type: String

Resources:
  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetLimit:
          Amount: 2
          Unit: USD
        BudgetName: !Sub '${ProjectName} Budget ${Environment}'
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 50
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref ContactEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref ContactEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 200
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref ContactEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 500
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref ContactEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 1000
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref ContactEmail

Outputs:
  BudgetId:
    Value: !Ref Budget
