AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    AllowedValues:
      - development
      - production
    Type: String

  PatientsTableName:
    Default: patients
    Type: String

Conditions:
  DevResource: !Equals [!Ref Environment, development]
  ProdResource: !Equals [!Ref Environment, production]

Resources:
  PatientsTableDev:
    Type: AWS::DynamoDB::Table
    Condition: DevResource
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: key
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref PatientsTableName
    DeletionPolicy: Retain

  PatientsTableProd:
    Type: AWS::DynamoDB::Table
    Condition: ProdResource
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: key
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref PatientsTableName
    DeletionPolicy: Retain
