Description: >
  Codepipeline, Build, and Deployment of Grace Medical Village client

Parameters:
  environment:
    AllowedValues:
      - development
      - production
    Description: Can be used to alter resources depending on environment
    Type: String

  githubBranch:
    AllowedValues:
      - master
      - production
    Type: String
    Description: The branch of the repo to continuously deploy. (dev)

  githubRepo:
    Default: gmv-patient-api
    Type: String

  githubToken:
    NoEcho: true
    Type: String

  githubUser:
    Default: Grace-Medical-Village
    Type: String

  resourcePrefix:
    AllowedValues:
      - gmv-dev-patient-api
      - gmv-prod-patient-api
    Type: String

  s3PipelineBucket:
    AllowedValues:
      - gmv-patient-api-pipeline-dev
      - gmv-patient-api-pipeline
    Type: String

  s3SourceBucket:
    AllowedValues:
      - patient-api-development-serverlessdeploymentbucke-zqef1ecxvht8
      - TODO
    Type: String

Resources:
  S3BucketForPipeline:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref s3PipelineBucket
    DeletionPolicy: Retain

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${resourcePrefix}-codebuild-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: '*'
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Resource:
                  - !Sub arn:aws:s3:::${s3PipelineBucket}/*
                  - !Sub arn:aws:s3:::${s3PipelineBucket}
                  - !Sub arn:aws:s3:::${s3SourceBucket}/*
                  - !Sub arn:aws:s3:::${s3SourceBucket}
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:ListBucket
              - Resource:
                  - arn:aws:apigateway:*::*
                Effect: Allow
                Action:
                  - apigateway:*
              - Resource:
                  - arn:aws:cloudformation:*::*
                Effect: Allow
                Action:
                  - cloudformation:*

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${resourcePrefix}-codepipeline-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource:
                  - !Sub arn:aws:s3:::${s3PipelineBucket}/*
                  - !Sub arn:aws:s3:::${s3PipelineBucket}
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:ListBucket
              - Resource: '*'
                Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - iam:PassRole

  CodeBuild:
    Type: AWS::CodeBuild::Project
    DependsOn:
      - S3BucketForPipeline
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: !Ref environment
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
        PrivilegedMode: false
      Name: !Sub ${resourcePrefix}-build
      ServiceRole: !Ref CodeBuildRole

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref s3PipelineBucket
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref s3PipelineBucket
      Stages:
        - Name: Source
          Actions:
            - Name: App
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref githubUser
                Repo: !Ref githubRepo
                Branch: !Ref githubBranch
                OAuthToken: !Ref githubToken
              OutputArtifacts:
                - Name: App
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 2
