AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an Amazon Route 53 hosted zone
Parameters:
  DomainName:
    AllowedValues:
      - gracemedicalvillagedev.com
      - gracemedicalvillage.com
    Type: String
  HostedZoneId:
    AllowedValues:
      - Z03413242K12VXBMESSYC
      - Z06243561BJW62E9DPALB
    Type: String

Resources:
  Domain:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub 'Hosted zone for ${DomainName}'
      Name: !Ref DomainName
  SslCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: DISABLED
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames:
        - !Sub '*.${DomainName}'
      ValidationMethod: DNS

Outputs:
  DomainName:
    Value: !Ref Domain
  SslCertificate:
    Value: !Ref SslCertificate
